# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0014_auto_20170405_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gear_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(choices=[(1, 'Weapon'), (3, 'Armor'), (4, 'Gloves'), (5, 'Boots'), (6, 'Left earing'), (7, 'Right earing'), (8, 'Left ring'), (9, 'Right ring'), (10, 'Necklace'), (11, 'Innerwear'), (19, 'Belt'), (20, 'Brooch')])),
                ('gearset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear.Gear')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('gearsets', models.ManyToManyField(to='gear.Gear')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear.Server'),
        ),
        migrations.AddField(
            model_name='gear',
            name='items',
            field=models.ManyToManyField(through='gear.Gear_Item', to='item.Item'),
        ),
    ]
