# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
