# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_auto_20170416_1303'),
        ('gear', '0004_remove_gear_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='armor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armor', to='item.Item'),
        ),
        migrations.AddField(
            model_name='gear',
            name='belt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belt', to='item.Item'),
        ),
        migrations.AddField(
            model_name='gear',
            name='boots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boots', to='item.Item'),
        ),
        migrations.AddField(
            model_name='gear',
            name='brooch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brooch', to='item.Item'),
        ),
        migrations.AddField(
            model_name='gear',
            name='gloves',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gloves', to='item.Item'),
        ),
        migrations.AddField(
            model_name='gear',
            name='innerwear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='innerwear', to='item.Item'),
        ),
        migrations.AddField(
            model_name='gear',
            name='left_earing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_earing', to='item.Item'),
        ),
        migrations.AddField(
            model_name='gear',
            name='left_ring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_ring', to='item.Item'),
        ),
        migrations.AddField(
            model_name='gear',
            name='necklace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='necklace', to='item.Item'),
        ),
        migrations.AddField(
            model_name='gear',
            name='right_earing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_earing', to='item.Item'),
        ),
        migrations.AddField(
            model_name='gear',
            name='right_ring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_ring', to='item.Item'),
        ),
        migrations.AddField(
            model_name='gear',
            name='weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to='item.Item'),
        ),
    ]
