# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0005_auto_20170416_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear_item',
            name='gearset',
        ),
        migrations.RemoveField(
            model_name='gear_item',
            name='item',
        ),
        migrations.DeleteModel(
            name='Gear_Item',
        ),
    ]
