# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0023_auto_20170416_1445'),
        ('gear', '0006_auto_20170416_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='circlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circlet', to='item.Item'),
        ),
    ]
