# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0007_gear_circlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.IntegerField(choices=[('Female', 0), ('Male', 1)], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='klass',
            field=models.IntegerField(choices=[('Warrior', 1), ('Lancer', 2), ('Slayer', 3), ('Berserker', 4), ('Sorcerer', 5), ('Archer', 6), ('Priest', 7), ('Mystic', 8), ('Reaper', 9), ('Gunner', 10), ('Brawler', 11), ('Ninja', 12), ('Valkyrie', 13)], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='race',
            field=models.IntegerField(choices=[('Human', 0), ('High elf', 1), ('Aman', 2), ('Castanic', 3), ('Popori', 4), ('Baraka', 5)], null=True),
        ),
    ]
