# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0008_auto_20170416_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Female'), (1, 'Male')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='klass',
            field=models.IntegerField(choices=[(1, 'Warrior'), (2, 'Lancer'), (3, 'Slayer'), (4, 'Berserker'), (5, 'Sorcerer'), (6, 'Archer'), (7, 'Priest'), (8, 'Mystic'), (9, 'Reaper'), (10, 'Gunner'), (11, 'Brawler'), (12, 'Ninja'), (13, 'Valkyrie')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='race',
            field=models.IntegerField(choices=[(0, 'Human'), (1, 'High elf'), (2, 'Aman'), (3, 'Castanic'), (4, 'Popori'), (5, 'Baraka')], null=True),
        ),
    ]
