# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0005_achievement'),
        ('gear', '0010_auto_20170519_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='achievements',
            field=models.ManyToManyField(through='achievement.Achievement', to='achievement.AchievementData'),
        ),
    ]
