# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('tooltip', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=200)),
                ('tradable', models.BooleanField()),
                ('warehouseStorable', models.BooleanField()),
                ('guildWarehouseStorable', models.BooleanField()),
                ('storeSellable', models.BooleanField()),
                ('enchantEnable', models.BooleanField()),
                ('boundType', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('combatItemType', models.CharField(max_length=20)),
                ('requiredEquipmentType', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('rareGrade', models.IntegerField()),
            ],
        ),
    ]
