# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='combatItemType',
            field=models.CharField(max_length=40),
        ),
    ]
