# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20170326_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdata',
            name='type',
        ),
    ]
