# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20170404_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdata',
            name='tradable',
        ),
        migrations.AddField(
            model_name='itemdata',
            name='tradeable',
            field=models.BooleanField(default=False),
        ),
    ]
