# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20170404_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
