# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_auto_20170404_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
