# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20170404_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdata',
            old_name='equipmentData',
            new_name='equipdata',
        ),
    ]
