# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_auto_20170405_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tooltip', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='bonuses',
            field=models.ManyToManyField(to='item.Passivity'),
        ),
        migrations.AddField(
            model_name='itemdata',
            name='passivity',
            field=models.ManyToManyField(to='item.Passivity'),
        ),
    ]
