# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_auto_20170405_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passivity',
            name='tooltip',
            field=models.CharField(max_length=1000),
        ),
    ]
