# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_auto_20170414_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='itemdata',
        ),
    ]
