# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_auto_20170414_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
