# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
        ('item', '0017_item_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gear.Server'),
            preserve_default=False,
        ),
    ]
