# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_item_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='crystal1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='crystal2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='crystal3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='crystal4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='enchant',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='feedstock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemLevel',
            field=models.IntegerField(null=True),
        ),
    ]
