# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_auto_20170416_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemdata',
            new_name='data',
        ),
    ]
