# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0023_auto_20170416_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDataPassivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='ItemPassivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        # migrations.AlterField(
        #     model_name='item',
        #     name='bonuses',
        #     field=models.ManyToManyField(through='item.ItemPassivity', to='item.Passivity'),
        # ),
        # migrations.AlterField(
        #     model_name='itemdata',
        #     name='passivity',
        #     field=models.ManyToManyField(through='item.ItemDataPassivity', to='item.Passivity'),
        # ),
        migrations.AddField(
            model_name='itempassivity',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item'),
        ),
        migrations.AddField(
            model_name='itempassivity',
            name='passivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Passivity'),
        ),
        migrations.AddField(
            model_name='itemdatapassivity',
            name='itemdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.ItemData'),
        ),
        migrations.AddField(
            model_name='itemdatapassivity',
            name='passivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Passivity'),
        ),
    ]
