# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0024_auto_20170417_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bonuses',
        ),
        migrations.RemoveField(
            model_name='itemdata',
            name='passivity',
        ),
        migrations.AddField(
            model_name='item',
            name='passivity',
            field=models.ManyToManyField(through='item.ItemPassivity', to='item.Passivity'),
        ),
    ]
