# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0025_auto_20170417_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdata',
            name='passivity',
            field=models.ManyToManyField(through='item.ItemDataPassivity', to='item.Passivity'),
        ),
    ]
