# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0027_auto_20170417_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='awkened',
            new_name='awakened',
        ),
    ]
