# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archievement',
            new_name='Achievement',
        ),
    ]
