# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0003_auto_20170520_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievement',
            new_name='AchievementData',
        ),
    ]
